### ISSUE TITLE
new issue 5/20/2021

### ISSUE THREAD

**Issue by lawrence1986101** [RandomNinjaAtk/docker-locast2tuner#1]
my OS is unraid well unraid said it had an update now it will not pull the File

TOTAL DATA PULLED: 0 B

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='locast2tuner' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'L2DUSER'='lawrence.crandall@yahoo.com' -e 'L2DPASS'='BadDodge1986' -e 'L2DZIP'='48202' -p '6077:6077/tcp' 'randomninjaatk/locast2tuner'
Unable to find image 'randomninjaatk/locast2tuner:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate is valid for localhost.localdomain, not registry-1.docker.io.
See 'docker run --help'.

The command failed.

**Comment by RandomNinjaAtk** [comment]
I don't host these services, nothing to be done. It's either a problem with your server and connection. Or a global problem.

**Comment by RandomNinjaAtk** [comment]
Updated to the new version without any issues, must be a local problem on your end.

**Comment by lawrence1986101** [comment]
im sorry guys this was my fault something happen to my setting in my pfsence box I'm so sorry for wasting yalls time normally I never touch the thing normally I just ignore it until I cant LMFAO this was one of them times I couldn't ignore I'm am so sorry it is now working like it should 
    On Friday, May 21, 2021, 01:42:42 PM EDT, RandomNinjaAtk ***@***.***> wrote:  
 
 


Updated to the new version without any issues, must be a local problem on your end.
