### ISSUE TITLE
add parameters

### ISSUE THREAD

**Issue by warrentc3** [RandomNinjaAtk/docker-locast2tuner#2]
Thanks for putting this out the hub!
It would be very helpful if params for remap and tuner count were also present.

**Comment by RandomNinjaAtk** [comment]
Hmm, well tuner count is set to the maximum available from locast... (I believe). So unless you wanted to decrease it, not sure why a change would be needed.

I can look into the params for remap, I haven't had a need for it.

**Comment by RandomNinjaAtk** [comment]
This repo is being archived, please feel free to re-open the request on the repo: https://github.com/wouterdebie/locast2tuner
